/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      colors: {
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-bright": "#31394d",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bfc8ca",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        outline: "#899295",
        "outline-variant": "#3f484a",
        "surface-tint": "#8ed1df",
        primary: "#8ed1df",
        "on-primary": "#00363e",
        "primary-container": "#579ba8",
        "on-primary-container": "#002f36",
        "inverse-primary": "#1c6774",
        secondary: "#b7c8e1",
        "on-secondary": "#213145",
        "secondary-container": "#3a4a5f",
        "on-secondary-container": "#a9bad3",
        tertiary: "#fbb983",
        "on-tertiary": "#4d2600",
        "tertiary-container": "#be8453",
        "on-tertiary-container": "#432100",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        background: "#0b1326",
        "on-background": "#dae2fd",
        "surface-variant": "#2d3449",
        "bullish-green": "#8ed1df",
        "bearish-red": "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        margin: "32px",
        "container-max": "1440px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        geist: ["Geist", "system-ui", "sans-serif"],
        manrope: ["Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Roboto Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};
