import type { Metadata } from "next";
import { Sparkles, AlertTriangle } from "lucide-react";
import { SiteHeader } from "@/components/SiteStructure";
import { PriceTicker } from "@/components/PriceTicker";
import { generateDailyBriefing } from "@/lib/ai";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export const metadata: Metadata = {
  title: "Daily Market Briefing | CryptoFlowCheck",
  description:
    "Your daily crypto market briefing — BTC and ETH momentum, the Fear & Greed Index, and the day's standout movers distilled into one concise, skimmable read.",
  alternates: { canonical: "/briefing" },
};

function formatGeneratedAt(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: "UTC",
  }) + " UTC";
}

export default async function BriefingPage() {
  const briefing = await generateDailyBriefing();
  const isFallback = briefing.source === "fallback";

  return (
    <div className="min-h-screen bg-bg-dark">
      <SiteHeader />
      <PriceTicker />

      <main className="max-w-container-max mx-auto px-gutter py-12">
        <header className="mb-8">
          <div className="flex items-center gap-2 mb-3">
            <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-primary/10 text-primary text-[10px] font-bold uppercase tracking-widest">
              <Sparkles className="w-3 h-3" /> Daily Briefing
            </span>
            <time
              className="text-on-surface-variant text-xs font-mono"
              dateTime={briefing.generatedAt}
            >
              {briefing.day}
            </time>
          </div>
          <h1 className="font-geist text-headline-lg font-bold text-on-surface">
            What&apos;s moving the market <span className="text-primary">today</span>
          </h1>
        </header>

        <article className="glass-panel p-stack-lg rounded-xl border-outline-variant/30">
          <p className="text-on-surface text-lg leading-relaxed">{briefing.summary}</p>

          {briefing.bullets.length > 0 && (
            <ul className="mt-6 space-y-3">
              {briefing.bullets.map((b, i) => (
                <li key={i} className="flex gap-3 text-on-surface-variant">
                  <span
                    aria-hidden="true"
                    className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary"
                  />
                  <span className="leading-relaxed">{b}</span>
                </li>
              ))}
            </ul>
          )}

          <footer className="mt-8 pt-5 border-t border-outline-variant/30 flex flex-wrap items-center justify-between gap-3">
            <p className="text-on-surface-variant text-xs">
              {isFallback ? (
                <span className="inline-flex items-center gap-1.5 text-tertiary">
                  <AlertTriangle className="w-3.5 h-3.5" />
                  Live data summary — AI commentary will resume automatically.
                </span>
              ) : (
                <>Generated by the CryptoFlowCheck market desk.</>
              )}
            </p>
            {briefing.generatedAt && (
              <p className="text-on-surface-variant text-[11px] font-mono">
                Updated {formatGeneratedAt(briefing.generatedAt)}
              </p>
            )}
          </footer>
        </article>

        <p className="mt-6 text-on-surface-variant text-[11px] leading-relaxed max-w-2xl">
          For informational purposes only. Not Financial Advice (NFA). Markets are volatile;
          do your own research and trade at your own risk.
        </p>
      </main>
    </div>
  );
}
